### ISSUE TITLE
Web Audio API support

### ISSUE THREAD

**Issue by bhollis** [bfirsh/dynamicaudio.js#6]
`mozWriteAudio` has been phased out in favor of the much more complicated Web Audio API. It'd be nice if dynamicaudio.js tried to use Web Audio API as one of its fallbacks. The code would look something like this Gist: https://gist.github.com/bhollis/05fa5870d41d96e07aff

**Comment by webdevbyjoss** [comment]
hey, @bhollis. have you managed to get it work with Web Audio API? 
Currently looking for possibility to use HTML5 for sound output and found this thread, which is a year old already.

**Comment by bhollis** [comment]
Yes, as I mentioned, I'm using it on http://benhollis.net/games/gravedigger/play/. Here's the code I'm using: https://gist.github.com/bhollis/05fa5870d41d96e07aff

**Comment by webdevbyjoss** [comment]
You mentioned that "I also modified JSNES to write into two Float32Arrays instead of a single interleaved buffer in hopes of making the audio stuff more efficient (it's still a bit glitchy though)."

Here are mine changes regarding Web Audio API for JSNES  https://github.com/bfirsh/jsnes/pull/45 
 and I'm currently have the same idea on revising the JSNES sampling code to write into two Float32Arrays. 

Have you shared your JSNES changes somewhere?

**Comment by bhollis** [comment]
Looks like I didn't stick with that change - it must not have mattered much.

**Comment by webdevbyjoss** [comment]
added HTML5 WebAudio support https://github.com/bfirsh/dynamicaudio.js/pull/7 check this out

**Comment by bfirsh** [comment]
Boom. https://github.com/bfirsh/dynamicaudio.js/releases/tag/0.2
